name: Update forecast

on:
  schedule:
    - cron:  '5 12 * * *'   # 09:05 BRT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --quiet yfinance prophet

      - name: Run generator
        run: python scripts/generate_forecast.py

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add data/forecast.json
          if git diff-index --quiet HEAD; then
            echo "No changes"
          else
            git commit -m "chore: update forecast $(date -u '+%Y-%m-%d')" || true
            git push
          fi
